# toml file for general configuration of the streaming server

[schedule]
year = 2020
season = "FALL"

[database]
hostname = "api.wjrh.org"
port = 5432
database = "testdb"
user = "wjrh"
schedule_table = "schedule"
auth_table = "mountpoints"

# Add extra timeslots here

[[timeslot]]
shortname = "black-coffee"
time = "1w0h-8w1h"

[liquidsoap]
input_server = "api.wjrh.org"
input_port = 8000
output_server = "api.wjrh.org"
output_port = 8000
