version: '2.0'
services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  # the auth service is a nodejs/express web app responsible for authorizing
  # publish requests to the rtmp server
  auth:
    build: "./auth"
    ports:
      - 1980:80
    depends_on: [redis]
  
  # an nginx server with the rtmp module responsible for hosting rtmp streams
  # from remote djs. It is also responsible for invoking ffmpeg whenever a
  # stream is created to transcode into mp3 and publish to the icecast server
  rtmp:
    image: "alfg/nginx-rtmp"
    # build: "./docker-nginx-rtmp"
    ports:
      - 1935:1935
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf.template"
    depends_on: [auth, redis]

  # the icecast server
  # icecast:
  #   build: ./icecast
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - "./icecast/icecast.xml:/etc/icecast2/icecast.xml"

  liquidsoap:
    build: https://github.com/radiorabe/docker-liquidsoap.git
    environment: ['TZ=America/New_York']
    volumes:
      - "./liquidsoap/src:/var/lib/liquidsoap"
    command: "main.liq"
    ports:
      - 9000:9000
