#!/bin/bash

# Make a new user and work directory for the daemon to use
mkdir -p /etc/liquidsoap
useradd liquidsoap_daemon

# give the the new user ownership of the work directory
chown -R liquidsoap_daemon /etc/liquidsoap

# copy liquidsoap source code into work directory
cp liquidsoap/main.liq /etc/liquidsoap/main.liq
cp liquidsoap/passwords.liq /etc/liquidsoap/passwords.liq

# copy service file into /etc/systemd/system
cp servicefile /etc/systemd/system/remote_studio.service

# enable and start daemon
systemctl enable remote_studio
systemctl restart remote_studio
