[package]
name = "auth-new"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide="0.16.0"
clap="2.33"
async-std={version="1.6.2", features=["attributes"]}
